"""Added last updated

Revision ID: c14ae337d095
Revises: 
Create Date: 2021-02-10 17:55:50.330135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14ae337d095'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_created_date', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_hashed_password', table_name='users')
    op.drop_index('ix_users_last_login', table_name='users')
    op.drop_table('users')
    op.add_column('releases', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_releases_last_updated'), 'releases', ['last_updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_releases_last_updated'), table_name='releases')
    op.drop_column('releases', 'last_updated')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=True),
    sa.Column('profile_image_url', sa.VARCHAR(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_last_login', 'users', ['last_login'], unique=False)
    op.create_index('ix_users_hashed_password', 'users', ['hashed_password'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_index('ix_users_created_date', 'users', ['created_date'], unique=False)
    # ### end Alembic commands ###
